---
# Configure Jenkins 
- name: configure | Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

- name: configure | Wait for Jenkins to start up before proceeding.
  wait_for: host={{ hostname }} port=8080 timeout=300

- name: configure | Download the jenkins-cli jarfile from the Jenkins server.
  get_url: url=http://{{ hostname }}:8080/jnlpJars/jenkins-cli.jar dest={{ jenkins_jar_location }}
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 5