---
# Install Jenkins.

- name: Check that Jenkins repo is installed.
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key: state=present key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Check if Jenkins is installed.
  yum: pkg=jenkins state=installed

- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

- name: Wait for Jenkins to start up before proceeding.
  wait_for: host={{ hostname }} port=8080 timeout=300

- name: Download the jenkins-cli jarfile from the Jenkins server.
  get_url: url=http://{{ hostname }}:8080/jnlpJars/jenkins-cli.jar dest={{ jenkins_jar_location }}
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 5

- name: Create Jenkins updates folder.
  file: path=/var/lib/jenkins/updates owner=jenkins group=jenkins mode=0755 state=directory

- name: Update Jenkins plugin data.
  shell:
    curl -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
    creates=/var/lib/jenkins/updates/default.json

- name: Permissions for default.json updates info.
  file: path=/var/lib/jenkins/updates/default.json owner=jenkins group=jenkins mode=0755

- name: Install Jenkins plugins.
  command: java -jar {{ jenkins_jar_location }} -s http://{{ hostname }}:8080/ install-plugin {{ item }} creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: jenkins_plugins
  notify: jenkins restart
